server:
  port: 83
dubbo:
  application:
    name: dubbo-comsumer
  protocol:
    name: dubbo
    port: 20883
  monitor:
    protocol: registry
  registry:
#    address: zookeeper://localhost:2181
    address: zookeeper://121.43.37.52:2181